name: sistem_parkir
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  device_preview: ^1.2.0
  permission_handler: ^12.0.0+1
  google_maps: ^8.1.1
  google_maps_flutter: ^2.12.2
  google_maps_flutter_web: ^0.5.12
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  http: ^1.4.0
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  http_parser: ^4.0.2
  path: ^1.8.3
  geolocator: ^14.0.0
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  